In [1]:
from pprint import pprint

from module_.utils.tf_agent import TF_Agent

/Users/seohasong/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
agent = TF_Agent()
agent.set_hyper_parameters(
    batch_size=8
)
agent.init_graph()
agent.init_sess()

In [ ]:
agent.run_sess()

In [9]:
result = agent.check_sen(10)
print(result[0])
print(result[1])
pprint(result[2])

100.00%
일본 특유 애수 적 감성 이 최대치 로 구현 된 영화 첫사랑 이 란 불변 과거 속 기억 에 고정 되 는 것 이 기 에 다만 기록 으로 남 을 뿐 덕분 에 그것 은 세상 에 물들 지 않 는 순수 함 그 자체 다
정재희 저격술 갓네 상귀 반크 키넌 갓네 클라우제비츠 월야
{'fake': {'label': (array([1, 0]),
                    array([[0.46521  , 0.5347901]], dtype=float32),
                    0.5),
          'valid': (array([1, 0]),
                    array([[0.9947983 , 0.00520167]], dtype=float32),
                    1.0)},
 'real': {'label': (array([0, 1]),
                    array([[0.46017233, 0.5398276 ]], dtype=float32),
                    1.0),
          'valid': (array([0, 1]),
                    array([[0.99479383, 0.00520618]], dtype=float32),
                    1.0)}}
